FROM python:3.10-slim-buster

WORKDIR /app

COPY . /app

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update --allow-releaseinfo-change \
 && apt-get install -y --no-install-recommends ca-certificates curl unzip \
 && pip install --no-cache-dir --upgrade pip awscli \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "app.py"]
